### ISSUE TITLE
搜索是什么逻辑？有些搜索不到

### ISSUE THREAD

**Issue by hanxiaofeng** [Bssn520/AnimationAutoUpdate#4]
如图：

<img width="704" alt="image" src="https://user-images.githubusercontent.com/10582931/213364531-dd333904-05ea-4ea2-9a08-09c056c3934a.png">

**Comment by Bssn520** [comment]
1. 搜索功能是Alist本身提供的，通过建立索引进行搜索；
2. 由于一些目录中文件太多(例如小雅Alist中的资源，是通过Alist v3挂载的)，而服务器带宽又比较小，造成构建索引时忽略了某些文件。
    - 暂时解决方法：
搜索地址：[搜索引擎](http://alist.xiaoya.pro/search?box=关键词&url=)
在上述地址搜索，找到路径之后回网站观看(当然，您也可以直接在[小雅Alist](http://alist.xiaoya.pro)观看, 不过由于其服务器位于海外，列表加载速度相对较慢。)
    - 注意：由于本项目只收录了小雅Alist中的《电影》、《电视剧》、《综艺》、《纪录片》，四项资源，所以其余的资源在本项目是找不到的。

**Comment by hanxiaofeng** [comment]
> 1. 搜索功能是Alist本身提供的，通过建立索引进行搜索；
> 2. 由于一些目录中文件太多(例如小雅Alist中的资源，是通过Alist v3挂载的)，而服务器带宽又比较小，造成构建索引时忽略了某些文件。
>    
>    * 暂时解决方法：
>      搜索地址：[搜索引擎](http://alist.xiaoya.pro/search?box=%E5%85%B3%E9%94%AE%E8%AF%8D&url=)
>      在上述地址搜索，找到路径之后回网站观看(当然，您也可以直接在[小雅Alist](http://alist.xiaoya.pro)观看, 不过由于其服务器位于海外，列表加载速度相对较慢。)
>    * 注意：由于本项目只收录了小雅Alist中的《电影》、《电视剧》、《综艺》、《纪录片》，四项资源，所以其余的资源在本项目是找不到的。

好的，了解了，感谢分享
